### ISSUE TITLE
HTTP Factory for Guzzle is deprecated, we should  switch to GuzzleHttp\Psr7\HttpFactory

### ISSUE THREAD

**Issue by Lawri-van-Buel** [MilesChou/psr#2]
As announced on [http-interop/http-factory-guzzle](https://github.com/http-interop/http-factory-guzzle)
HTTP Factory for Guzzle

HTTP factory implemented for [Guzzle](https://github.com/guzzle/psr7).

NOTE: guzzlehttp/psr7 includes an HTTP factory implementation starting with version 2.0. Please use the official factory if your project can use "guzzlehttp/psr7": "^2.0".

**Comment by MilesChou** [comment]
Thanks for PR
